version: '3.8'
services:
  run_migration:
    profiles:
      - config_environment
    depends_on: 
      - mysql
    build:
      context: ../
      dockerfile: Dockerfile
      target: dev
    environment:
      NODE_ENV: development
    env_file: ../.env.dev
    networks:
      - pokeapp
    command: ["pnpm", "dev:knex:migrate"]
    
  pokeapp:
    profiles:
      - dev
    build:
      context: ../
      dockerfile: Dockerfile
      target: dev
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
    env_file: ../.env.dev
    develop:
      watch:
        - path: ../src
          action: sync
          target: /home/node/app/src
          ignore:
            - .git
            - node_modules
        - action: rebuild
          path: package.json
    depends_on:
      - mysql
    networks:
      - pokeapp
  mysql:
    image: mysql:9.3.0
    env_file: ../.env.dev
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - pokeapp
    restart: always

volumes:
  mysql-data:
networks:
  pokeapp:
    driver: bridge