# Criará replica de vários pod
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pokeappreplicaset
  labels:
    app: pokeapp-replica
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pokeapp
  template:
    metadata:
      labels:
        app: pokeapp
    spec:
      containers:
        - name: myapp
          image: ghcr.io/rodrigo1999/pokeapp
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: DATABASE_TYPE
              value: "json"

---

apiVersion: v1
kind: Service
metadata:
  name: pokeapp-service
spec:
  type: ClusterIP
  selector:
    app: pokeapp
  ports:
  - port: 5000 # Port taht i expose of service
    protocol: TCP
    targetPort: 5000 # Port of pod
