apiVersion: v1
kind: ConfigMap
metadata:
  name: pokeapp-env
data:
  DATABASE_TYPE: mysql
  DATABASE_NAME: pokeapp
  DATABASE_USER: root
  DATABASE_PASSWORD: "654321"
  DATABASE_PORT: "3306"
  DATABASE_SSL: "false"
  DATABASE_HOST: mysql
