### Listar todos os pokemons capturados
GET {{BASE_URL}}/pokemons
content-type: application/json

### Captura um pokemon
POST {{BASE_URL}}/pokemons/capture
content-type: application/json

{
    "poke_id": "poke_19",
    "cep": "64640000"
}

### Evolui um pokemon
PUT {{BASE_URL}}/pokemons/evolve/1
content-type: application/json

### Recaptura um pokemon
POST {{BASE_URL}}/pokemons/recapture
content-type: application/json

{
    "poke_id": "poke_19",
    "cep": "64607715"
}

### Libera/abandona um pokemon
DELETE {{BASE_URL}}/pokemons/release/r0o6l24f628
content-type: application/json